### ISSUE TITLE
Unsupported device: Aqara Wireless Remote Switch

### ISSUE THREAD

**Issue by sonicmingit** [Danielhiversen/PyXiaomiGateway#86]
The device testing static and dynamic :
{'cmd': 'read_ack', 'model': 'vibration', 'sid': '158d0002a4ab83', 'short_id': 2908, 'data': '{"voltage":3185}'}

New Aqara Wireless Remote Switch :
{'cmd': 'read_ack', 'model': 'remote.b286acn01', 'sid': '158d00028829a9', 'short_id': 6697, 'data': '{"voltage":3125}'}
https://www.aqara.com/en/86plug.html

**Comment by syssi** [comment]
If you interact with the devices do you see responses with additional data next to the voltage? If not the gateway firmware doesn't support the device and we have to wait for an update.

**Comment by dlashua** [comment]
I have a vibration sensor coming soon and am familiar with the Xiaomi Home Assistant integration. I can submit a PR to add support for it. I don't have the new Wireless remote switch, however. I can add support for it as well if you can send me the JSON payloads similar to what you sent above for all the different uses (single press, double press, long press). Also, I'll need to know if you have the one button, or two button model. If you have the two button, also send the JSON payload for pressing both buttons at once.

**Comment by syssi** [comment]
@dlashua Feel free to submit a PR. We are happy about support!

**Comment by syssi** [comment]
Vibration Sensor: https://github.com/Danielhiversen/PyXiaomiGateway/issues/87

**Comment by dlashua** [comment]
I have this working in development. The changes required to PyXiaomiGateway are very small. A simple addition of "vibration" to the list at device_types.sensor.

The changes to xiaomi_aqara are fairly simple as well. I'm able to see the various data elements reported by this sensor. However, this doesn't handle the device in any way that is useful.

The data elements available are:

status: this is either tilt, vibrate, or free_fall

The device continues to report "vibrate" every minute or so when it is on a vibrating surface. However, there is no report when it stops vibrating. There is not a "no_motion" report like we see with the PIR sensors. This means that reporting when vibration stops will require a timer of slightly over 1 minute, most likely implemented in the sensor/xiaomi_aqara Entity code. 

"tilt" happens after the device has been tilted.

"free_fall" happens after the device has been dropped at least 3 inches or so.


bed_activity: this reports a number. It seems to be related to vibration. It might correspond to how much movement was seen during the last reporting period. When sitting on my clothes dryer while it was running, it reported the same number for many reports which seem to come about one minute apart. The numbers reported from 72 to 214. Often the same number would report for multiple minutes. A 0 is never reported. 

coordination: this is three numbers separated by commas. It is reported without any regularity. When in the same spot on my running dryer, it reported different sets of numbers that were fairly close to one another: "51,-24,1207" and "47,-31,1233". When I then walked it to another room and placed it on my desk it reported "-935,40,220", but also, at another time, while near my desk, "5,46,1233"

final_tilt_angle: after changing the angle of the sensor, this will report along with a "tilt" status. No matter how I move the sensor, however, can I determine exactly what the data corresponds to.

**Comment by dlashua** [comment]
Altering the Home Assistant code to add a new sensor to an existing platform is fairly simple, something I've done before. However, because there are no other sensors like this one, the knowledge of Home Assistant internals required to create these sensors (i.e. a binary sensor that reports as "on" when status is reported as "vibrate" any time within the last 1.5 minutes, but then reports as "off" when status hasn't said "vibrate" in the last 1.5 minutes) is knowledge I don't have.

Therefore, stuffing the values into various Home Assistant sensors and allowing the user to interpret them as they wish is something I can manage. But making the sensor truly useful without requiring a lot of automation code that would be repeated by every user is is more of a task than I'm prepared for. If I'm going to do this myself, I'll implement it in NodeJS and report the data using MQTT, which is not really a Home Assistant component at all, but, for my use, I can get the end result much quicker that way. Someone else with more Home Assistant internal knowledge should handle adding support for the "vibration" device.
